version: '3'
services:
  go:
    container_name: go-snippetreviews
    build: ./docker/golang
    volumes:
      - ./:/go/src/snippetreviews
    working_dir: /go/src/snippetreviews
    command: go run ./cmd/web
    environment:
      - SR_MYSQL=mysql
      - SR_MYSQL_DATABASE=snippetreviews
    ports:
      - "4000:4000"
    depends_on:
      - mysql
    networks:
      - snippetreviews
  mysql:
    container_name: mysql-snippetreviews
    build: ./docker/mysql
    healthcheck:
      test: ["CMD-SHELL", 'mysql --database=$$MYSQL_DATABASE --password=$$MYSQL_ROOT_PASSWORD --execute="SELECT count(table_name) > 0 FROM information_schema.tables;" --skip-column-names -B']
      interval: 30s
      timeout: 10s
      retries: 4
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: snippetreviews
    ports:
      - "3306:3306"
    networks:
      - snippetreviews
    volumes:
      - volume-mysql-snippetreviews:/vol/mysql
networks:
  snippetreviews:
volumes:
  volume-mysql-snippetreviews: