version: '3'
services:
  database:
    build:
      context: ./database
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: snippetreviews
      MYSQL_USER: web
      MYSQL_PASSWORD: pass
    container_name: snippetreviews-db
    tty: true
    ports:
      - "3306:3306"
  server:
    build:
      context: ./server
    volumes:
      - "./server/src/:/go/src/github.com/sysrex/snippetreviews/cmd/web/"
    container_name: snippetreviews-app
    ports:
      - "4000:4000"
    tty: true
    depends_on:
      - database